---
version: 2.1

executors:
  go-build:
    docker:
      - image: quay.io/getpantheon/go-build:latest
        auth:
          username: $QUAY_USER
          password: $QUAY_PASSWD

commands:
  save-go-mod-cache:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  restore-go-mod-cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}

  save-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - ./

  restore-workspace:
    steps:
      - attach_workspace:
          at: .

jobs:
  test:
    executor: go-build
    steps:
      - checkout
      - restore-go-mod-cache
      # run tasks
      - run: make lint
      - run: make test
      - run: make build
      # persist
      - save-go-mod-cache
      - save-workspace

  release:
    executor: go-build
    steps:
      - restore-workspace
      - restore-go-mod-cache
      - setup_remote_docker
      - run: docker login -u "$QUAY_USER" -p "$QUAY_PASSWD" quay.io
      - run: |
          curl -s https://api.github.com/repos/pantheon-systems/autotag/releases/latest | \
            grep browser_download | \
            grep -i linux | \
            cut -d '"' -f 4 | \
            xargs curl -o ~/autotag -L \
            && chmod 755 ~/autotag
      - run: ~/autotag
      - run: make release

workflows:
  version: 2
  primary:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
